name: Build and Deploy Flask API

on:
  push:
    branches:
      - main  # Adjust this branch name to match your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG="${{ github.sha }}"  # This is the tag you want to use
          docker build -t elviskimara/flask-app:${TAG} .
          docker push elviskimara/flask-app:${TAG}
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Docker container
        run: docker run -d -p 4001:8080 elviskimara/flask-app:${{ github.sha }}
